#include "lc_common.h"

enum LC_ADDON_FLAGS
{
	LC_ADDON_FLAG_NONE = 0X0000,
	LC_ADDON_FLAG_AUDIO = 0X0001,
	LC_ADDON_FLAG_ACODEC = 0X0002,
	LC_ADDON_FLAG_COLOR = 0X0004,
	LC_ADDON_FLAG_FONT = 0X0008,
	LC_ADDON_FLAG_IMAGE = 0X0010,
	LC_ADDON_FLAG_MEMFILE = 0X0020,
	LC_ADDON_FLAG_NATIVEDIALOG = 0X0040,
	LC_ADDON_FLAG_PHYSFS = 0X0080,
	LC_ADDON_FLAG_PRIMITIVES = 0X0100,
	LC_ADDON_FLAG_TTF = 0X0200
};

static const lc_string_int_pair_t LC_ADDON_FLAG_NAMES[LC_ADDON_FLAG_ID_COUNT] =
{
	{ LC_STRING_ADDON_AUDIO, LC_ADDON_FLAG_AUDIO },
	{ LC_STRING_ADDON_ACODEC, LC_ADDON_FLAG_ACODEC },
	{ LC_STRING_ADDON_COLOR, LC_ADDON_FLAG_COLOR },
	{ LC_STRING_ADDON_FONT, LC_ADDON_FLAG_FONT },
	{ LC_STRING_ADDON_IMAGE, LC_ADDON_FLAG_IMAGE },
	{ LC_STRING_ADDON_MEMFILE, LC_ADDON_FLAG_MEMFILE },
	{ LC_STRING_ADDON_DIALOG, LC_ADDON_FLAG_NATIVEDIALOG },
	{ LC_STRING_ADDON_PHYSFS, LC_ADDON_FLAG_PHYSFS },
	{ LC_STRING_ADDON_PRIMITIVES, LC_ADDON_FLAG_PRIMITIVES },
	{ LC_STRING_ADDON_TTF, LC_ADDON_FLAG_TTF }
};

int32_t lc_addon_flag_parse(o_stringview_t view)
{
	return lc_pair_array_flag_parse(LC_ADDON_FLAG_NAMES, LC_ADDON_FLAG_ID_COUNT, view, '|');
}

const char* lc_addon_flag_name(int32_t flag)
{
	for (size_t i = 0; i < LC_ADDON_FLAG_ID_COUNT; i++)
	{
		if (LC_ADDON_FLAG_NAMES[i].m_value == flag)
		{
			return LC_ADDON_FLAG_NAMES[i].m_string;
		}
	}

	return NULL;
}